### ISSUE TITLE
Request: Update ronn-ng formula

### ISSUE THREAD

**Issue by mcorossigo** [apjanke/homebrew-ronn-ng#2]
Hello @apjanke 
According to this line https://github.com/apjanke/homebrew-ronn-ng/blob/f235f04fed9e0bf1031dc8615b47f5275a699156/Formula/ronn-ng.rb#L4

the formula is installing version 0.8.0, while ronn-ng is currently at 0.9.1, and it's been for a while.
It's not a big deal since in the meantime I'm using the gem installation, but this tap is still suggested in the docs, and usually I prefer it.

Thanks!

**Comment by apjanke** [comment]
d'oh! Fixed by updating to Ronn-NG 0.9.1 in https://github.com/apjanke/homebrew-ronn-ng/commit/e9b1e8581920add3a827da418501bfca0c060517.

```
$ brew info ronn-ng
apjanke/ronn-ng/ronn-ng: stable 0.9.1, HEAD
```

Thanks for the reminder!
